name: Release

on:
    workflow_dispatch:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write # needed to push the branch + create commits
    pull-requests: write # needed to open/update the PR
    packages: write # needed for publish to npm.pkg.github.com

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Enable corepack
              run: corepack enable

            - name: Check tool versions
              run: |
                node --version
                corepack --version
                yarn --version

            - name: Install Dependencies
              run: yarn install --immutable

            # - name: Ensure repo has a valid changeset before publishing
            #   run: |
            #       git fetch origin --tags || true
            #       yarn changeset status --verbose

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              # with:
              #     # This expects you to have a script called release which does a build for your packages and calls changeset publish
              #     publish: yarn changeset tag
              with:
                # This expects you to have a script called release which does a build for your packages and calls changeset publish
                publish: yarn changeset publish              
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # - name: Check tool versions
            #   run: |
            #     node --version
            #     corepack --version
            #     yarn --version

            # - name: Install dependencies
            #   run: yarn install --immutable

            # - name: Prepare branch for Changesetsffff
            #   run: |
            #     git fetch origin main
            #     git branch main origin/main

            # - name: Verify that a changeset exists
            #   run: |
            #     # git fetch origin main --depth=1 || true
            #     # git branch main origin/main || true

            #     # git fetch origin --tags || true
            #     # yarn changeset status --verbose
            #     # git fetch origin --tags
            #     # yarn changeset status --verbose
            #     yarn changeset status --since=origin/main --verbose